name: lint
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    awesome-lint:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
            - "readme_ko.md"
            - "readme_ru.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
          with:
            fetch-depth: 0
        - name: "linting: ${{ matrix.files }}"
          run: npx awesome-lint ${{ matrix.files }}
    awesome-bot:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
            - "readme_ko.md"
            - "readme_ru.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
        - name: "install awesome-bot"
          run: gem install awesome_bot
        - name: "linting: ${{ matrix.files }}"
          run: awesome-bot ${{ matrix.files }}
