name: lint
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    awesome-lint:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
            - "readme_ko.md"
            - "readme_ru.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
          with:
            depth: 0
        - name: "linting: ${{ matrix.files }}"
          uses: jthegedus/github-action-awesome-lint@v0.1.0
          with:
            args: ${{ matrix.files }}
    awesome-bot:
      name: "lint: awesome-bot"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
    #     - name: "lint: awesome-bot"
    #       uses: jthegedus/github-action-awesome-bot@v0.1.0 # I trust me, so will happily use Tag versioning over commit_sha
